name: shared_preferences_content_provider
description: A Flutter package support share data between multiple application via content provider.
version: 0.0.1
homepage: https://github.com/zhgwu/shared_preferences_content_provider

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.zhgwu.shared_preferences_content_provider
        pluginClass: SharedPreferencesContentProviderPlugin
